# Generated by Django 5.0.8 on 2024-09-04 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_code', models.BigIntegerField()),
                ('phone_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('middlename', models.CharField(blank=True, max_length=100, null=True)),
                ('first_order_key', models.CharField(max_length=255)),
                ('second_order_key', models.CharField(max_length=255)),
                ('reception_code', models.BigIntegerField(unique=True)),
                ('start_time', models.DateTimeField()),
                ('processed_for_today', models.BooleanField(default=False)),
                ('processed_for_tomorrow', models.BooleanField(default=False)),
                ('calltime_for_tomorrow', models.DateTimeField(blank=True, null=True)),
                ('calltime_for_today', models.DateTimeField(blank=True, null=True)),
                ('upload_time', models.DateTimeField()),
                ('is_added', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_key', models.CharField(max_length=255)),
                ('status_id', models.IntegerField(blank=True, null=True)),
                ('audio_link', models.TextField(blank=True, null=True)),
                ('call_type', models.CharField(choices=[('today', 'Сегодня'), ('tomorrow', 'Завтра')], max_length=10)),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='reminder.reception')),
            ],
        ),
    ]
