# Generated by Django 5.0.8 on 2024-09-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='first_order_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reception',
            name='second_order_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
