# Generated by Django 5.0.8 on 2024-09-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_alter_reception_first_order_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='first_audio_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reception',
            name='first_status_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reception',
            name='second_audio_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reception',
            name='second_status_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
